# Generated by Django 3.1 on 2020-08-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200815_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='default-pfp.jpg', upload_to='profile_pics'),
        ),
    ]
