# Generated by Django 3.1 on 2020-08-16 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_profile_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='economicScore',
            field=models.IntegerField(blank=True, default=-5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='gaveValues',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='socialScore',
            field=models.IntegerField(blank=True, default=-5),
            preserve_default=False,
        ),
    ]
