# Generated by Django 3.1 on 2020-08-16 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200815_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='economicScore',
            field=models.IntegerField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='socialScore',
            field=models.IntegerField(blank=True, default=True),
        ),
    ]
