# Generated by Django 3.1 on 2020-08-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='header',
            field=models.ImageField(default='default.jpg', upload_to='article-headers'),
        ),
    ]
