# Generated by Django 3.1 on 2020-08-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_article_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='header_caption',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='header',
            field=models.ImageField(default='default-header.jpg', upload_to='article-headers'),
        ),
    ]
