# Generated by Django 3.1 on 2020-08-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_article_headline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='header_caption',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='headline',
            field=models.CharField(max_length=100),
        ),
    ]
